### ISSUE TITLE
Error building with Boost v1.62.0.1

### ISSUE THREAD

**Issue by knkrth** [geysercoin/geysercoin#1]
Hi, While Making it gives make error.

`makefile.unix:179: recipe for target 'obj/chainparams.o' failed
make: *** [obj/chainparams.o] Error 1`

**Comment by geysercoin** [comment]
what version of the system? where you compile?

**Comment by knkrth** [comment]
Ubuntu 17 I downgrade to Ubuntu 16 everything works fine now.
